### PR TITLE
Parse active duration and distance

### PR DESCRIPTION
**Pull request by quamen**
Throwing this up into a PR for testing.

I'm not sure if the active_duration or end_time attributes are getting the correct values. One of them is probably wrong so it would be nice if @plasticine could test this out locally with a TCX file that you know the real values of and let me know how you go.

I'm going to do the same by downloading some files from garmin connect to play with later.

### CODE REVIEW

**Comment by plasticine** [comment]
Sicko, nice work. Will have a geez and run some files past it.

**Comment by plasticine** [comment]
OK, so I _think_ the numbers are right, but at the moment I’m testing old files. Going to go for a run today, note time/distance exactly and then re-test. I think it is pulling out active duration.

But tentative green light—looking good so far. :+1:

**Comment by plasticine** [comment]
@quamen Any reason for this not to be merged?

**Comment by quamen** [comment]
Nope. If we're happy with the numbers then merge away.

**Pull request merged**
